### ISSUE TITLE
code not available

### ISSUE THREAD

**Issue by hanluxq** [plkumjorn/FIND#1]

**Comment by plkumjorn** [comment]
Thank you for your interest in our paper. The code is available at https://github.com/plkumjorn/FIND. You may either clone the repository to your local machine or download a zip file of the code using the green button as shown in the image below. If you still cannot access it, please provide additional details (e.g., the screenshot), and I'll try my best to assist you.

![image](https://user-images.githubusercontent.com/7281369/234755630-272a1ff2-b1ab-4d73-a70f-22f95752a7d0.png)

**Comment by hanluxq** [comment]
Thank you for your reply. When I run debugging_20Newsgroups.ipynb, an error has been reported. Does find refer to a package or the find folder? I did not find the corresponding method in the find folder, looking forward to your reply, thank you!
```
-------------------------------------------------- -------------------------
NameError Traceback (most recent call last)
<ipython-input-18-d606ba9c50cc> in <cell line: 5>()
       3 data_1 = pickle.load(open(DATA_PATH + f'all_data_{MAIN_DATASET}.pickle', 'rb'))
       4 class_names = data_1['class_names']
----> 5 X_train_1, X_validate_1, X_test_1 = find.get_data_matrix(data_1['text_train'], word2index, MAXLEN), \
       6 find.get_data_matrix(data_1['text_validate'], word2index, MAXLEN), \
       7 find.get_data_matrix(data_1['text_test'], word2index, MAXLEN)

NameError: name 'find' is not defined
```

**Comment by hanluxq** [comment]
I have solved the problem, thanks!

**Comment by hanluxq** [comment]
I have solved the problem, thanks!
